# Generated by Django 4.0.1 on 2022-01-16 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('data_recebimento', models.DateField(default=django.utils.timezone.now)),
                ('data_recebimento_esperado', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo_receita', models.CharField(max_length=200)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
