# Generated by Django 4.0.1 on 2022-01-16 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.CharField(max_length=200)),
                ('tipo_conta', models.CharField(max_length=200)),
                ('instituicao_financeira', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('data_pagamento', models.CharField(max_length=200)),
                ('data_pagamento_esperado', models.CharField(max_length=200)),
                ('tipo_despesa', models.CharField(max_length=200)),
                ('conta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('data_recebimento', models.CharField(max_length=200)),
                ('data_recebimento_esperado', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo_receita', models.CharField(max_length=200)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Receitas',
        ),
    ]
