# Generated by Django 4.0.1 on 2022-01-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contas_despesas_receita_delete_receitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='conta',
            field=models.CharField(max_length=200),
        ),
    ]
